import { useEffect, useState } from "react";
import { FiSearch } from "react-icons/fi";
import api from "../../api/axios";

export default function PublicContentPage({ type, title, description, actionLabel = "Explore" }) {
  const [items, setItems] = useState([]); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [meta, setMeta] = useState({ totalPages: 1 }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const request = window.setTimeout(async () => { setLoading(true); try { const { data } = await api.get(`/content/public/${type}`, { params: { search, page, limit: 9, sort: "newest" } }); setItems(data.data); setMeta(data); setError(""); } catch { setError("Unable to load content right now."); } finally { setLoading(false); } }, 250); return () => window.clearTimeout(request); }, [page, search, type]);
  return <main><section className="bg-gray-100 py-20"><div className="mx-auto max-w-7xl px-6"><h1 className="text-5xl font-black">{title}</h1><p className="mt-4 max-w-3xl text-lg text-gray-500">{description}</p></div></section><section className="mx-auto max-w-7xl px-6 py-10"><label className="relative block"><FiSearch className="absolute left-4 top-4 text-gray-400"/><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder={`Search ${title.toLowerCase()}...`} className="w-full rounded-xl border px-5 py-4 pl-11 outline-none focus:ring-2 focus:ring-red-600"/></label>{error && <p className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}{loading ? <p className="py-16 text-center text-gray-500">Loading…</p> : !items.length ? <p className="py-16 text-center text-gray-500">No published {title.toLowerCase()} found.</p> : <div className="mt-10 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item._id} className="overflow-hidden rounded-2xl bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><img src={item.image || "https://placehold.co/800x500/e5e7eb/475569?text=SoleVerse"} alt={item.title} className="h-56 w-full object-cover"/><div className="p-5"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold uppercase text-red-600">{item.category || item.section || type}</span>{item.featured && <span className="text-xs font-semibold text-amber-600">Featured</span>}</div><h2 className="mt-3 text-xl font-bold">{item.title}</h2><p className="mt-3 line-clamp-3 text-sm text-gray-500">{item.summary || item.content}</p><p className="mt-5 text-sm font-semibold text-gray-900">{actionLabel} →</p></div></article>)}</div>}{meta.totalPages > 1 && <div className="mt-12 flex justify-center gap-3"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Previous</button><span className="px-4 py-2 text-sm text-gray-500">Page {page} of {meta.totalPages}</span><button disabled={page === meta.totalPages} onClick={() => setPage(page + 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Next</button></div>}</section></main>;
}
