import { useState } from "react";
import { FiMail } from "react-icons/fi";
import api from "../../api/axios";

export default function Newsletter({ settings = {}, sectionSettings = {} }) {
  const [email, setEmail] = useState(""); const [message, setMessage] = useState("");
  if (!settings.enabled) return null;
  const submit = async (event) => { event.preventDefault(); try { await api.post("/cms/public/subscribe", { email }); setMessage("You’re on the list."); setEmail(""); } catch (error) { setMessage(error.response?.data?.message || "Please try again."); } };
  return <section className="mx-auto max-w-[1600px] px-5 py-10 sm:px-10 sm:py-14"><div style={{ backgroundColor: settings.backgroundColor || "#090909", backgroundImage: settings.backgroundImage ? `linear-gradient(90deg,rgba(0,0,0,.86),rgba(0,0,0,.35)), url(${settings.backgroundImage})` : undefined }} className="overflow-hidden rounded border border-white/10 bg-cover bg-center p-7 text-white shadow-2xl sm:flex sm:items-center sm:gap-8 sm:p-9"><span className="mb-5 grid h-12 w-12 place-items-center border border-white/20 text-2xl sm:mb-0"><FiMail/></span><div className="flex-1"><h2 className="text-2xl font-black tracking-[-.045em]">{settings.title || "Join the Culture."}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/65">{settings.subtitle || "Get the latest sneaker news, exclusive drops, and special offers straight to your inbox."}</p></div><form onSubmit={submit} className="mt-6 flex w-full max-w-xl sm:mt-0"><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder={settings.placeholder || "Enter your email"} className="min-w-0 flex-1 bg-white/10 px-4 py-3 text-sm text-white outline-none placeholder:text-white/45"/><button className="bg-[#eee0c9] px-5 text-xs font-black uppercase text-black hover:bg-white">{settings.buttonText || "Subscribe"}</button></form>{message && <p className="w-full text-sm text-white/70 sm:w-auto">{message}</p>}</div></section>;
}
