import { useCallback, useEffect, useState } from "react";
import { FiImage, FiPlus, FiSearch, FiTrash2 } from "react-icons/fi";
import api from "../../api/axios";
import { useToast } from "./Toast";

const Button = ({ children, className = "", ...props }) => <button className={`inline-flex items-center justify-center gap-2 rounded-xl px-3.5 py-2.5 text-sm font-semibold disabled:opacity-50 ${className}`} {...props}>{children}</button>;
const date = (value) => new Date(value).toLocaleDateString();

export function AuthorsPage() {
  const [items, setItems] = useState([]), [name, setName] = useState(""), [bio, setBio] = useState(""), [avatar, setAvatar] = useState(null), [editing, setEditing] = useState(null), [search, setSearch] = useState(""); const toast = useToast();
  const load = useCallback(() => api.get("/cms/authors", { params: { search, limit: 50 } }).then(({ data }) => setItems(data.data)).catch(() => toast("Could not load authors", "error")), [search, toast]); useEffect(() => { load(); }, [load]);
  const save = async (event) => { event.preventDefault(); const payload = new FormData(); payload.append("name", name); payload.append("bio", bio); if (avatar) payload.append("avatar", avatar); try { if (editing) await api.put(`/cms/authors/${editing._id}`, payload); else await api.post("/cms/authors", payload); toast(editing ? "Author updated" : "Author created"); setEditing(null); setName(""); setBio(""); setAvatar(null); load(); } catch (error) { toast(error.response?.data?.message || "Could not save author", "error"); } };
  const remove = async (item) => { if (!window.confirm(`Delete ${item.name}?`)) return; try { await api.delete(`/cms/authors/${item._id}`); toast("Author deleted"); load(); } catch { toast("Could not delete author", "error"); } };
  return <><header className="mb-7"><h2 className="text-2xl font-black">Authors</h2><p className="mt-1 text-sm text-slate-500">Manage contributor profiles and avatars.</p></header><div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={save} className="h-fit rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold">{editing ? "Edit author" : "New author"}</h3><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" className="field"/><textarea value={bio} onChange={(e) => setBio(e.target.value)} placeholder="Short biography" rows="4" className="field resize-y"/><label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-slate-300 p-3 text-sm"><FiImage/> {avatar?.name || "Upload avatar"}<input type="file" accept="image/*" onChange={(e) => setAvatar(e.target.files[0])} className="hidden"/></label><div className="mt-4 flex gap-2"><Button className="bg-indigo-600 text-white">Save</Button>{editing && <Button type="button" onClick={() => { setEditing(null); setName(""); setBio(""); }} className="border border-slate-200">Cancel</Button>}</div></form><section className="rounded-2xl border border-slate-200 bg-white"><div className="border-b p-3"><label className="relative block"><FiSearch className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search authors" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 text-sm"/></label></div><div className="divide-y">{items.map((item) => <div key={item._id} className="flex items-center justify-between gap-3 p-4"><div className="flex items-center gap-3"><img src={item.avatar || "https://placehold.co/80x80/e2e8f0/475569?text=SV"} alt="" className="h-10 w-10 rounded-full object-cover"/><div><p className="font-semibold">{item.name}</p><p className="line-clamp-1 text-xs text-slate-500">{item.bio || "No biography"}</p></div></div><div className="flex gap-2"><Button onClick={() => { setEditing(item); setName(item.name); setBio(item.bio); }} className="border border-slate-200">Edit</Button><Button onClick={() => remove(item)} className="text-rose-600"><FiTrash2/></Button></div></div>)}{!items.length && <p className="p-10 text-center text-sm text-slate-500">No authors yet.</p>}</div></section></div></>;
}

export function MediaPage() {
  const [items, setItems] = useState([]), [file, setFile] = useState(null), [alt, setAlt] = useState(""), [search, setSearch] = useState(""); const toast = useToast(); const load = useCallback(() => api.get("/cms/media", { params: { search, limit: 60 } }).then(({ data }) => setItems(data.data)).catch(() => toast("Could not load media", "error")), [search, toast]); useEffect(() => { load(); }, [load]); const upload = async (event) => { event.preventDefault(); if (!file) return; const body = new FormData(); body.append("file", file); body.append("alt", alt); try { await api.post("/cms/media", body); toast("Image uploaded"); setFile(null); setAlt(""); load(); } catch (error) { toast(error.response?.data?.message || "Upload failed", "error"); } }; const remove = async (item) => { if (!window.confirm("Delete this image?")) return; try { await api.delete(`/cms/media/${item._id}`); toast("Media deleted"); load(); } catch { toast("Could not delete media", "error"); } }; return <><header className="mb-7"><h2 className="text-2xl font-black">Media Library</h2><p className="mt-1 text-sm text-slate-500">Upload and reuse Cloudinary-hosted images.</p></header><form onSubmit={upload} className="mb-5 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><input required type="file" accept="image/*" onChange={(e) => setFile(e.target.files[0])} className="text-sm"/><input value={alt} onChange={(e) => setAlt(e.target.value)} placeholder="Alt text" className="rounded-xl border border-slate-200 px-3 text-sm"/><Button className="bg-indigo-600 text-white"><FiPlus/>Upload</Button></form><label className="relative mb-5 block max-w-md"><FiSearch className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search media" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 text-sm"/></label><div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5">{items.map((item) => <figure key={item._id} className="group relative overflow-hidden rounded-xl border border-slate-200 bg-white"><img src={item.url} alt={item.alt} className="aspect-square w-full object-cover"/><figcaption className="truncate p-2 text-xs text-slate-500">{item.alt || item.publicId}</figcaption><button onClick={() => remove(item)} className="absolute right-2 top-2 rounded-lg bg-white/90 p-2 text-rose-600 opacity-0 shadow group-hover:opacity-100"><FiTrash2/></button></figure>)}</div></>;
}

export function NewsletterPage() { const [items, setItems] = useState([]), [search, setSearch] = useState(""); const toast = useToast(); const load = useCallback(() => api.get("/cms/subscribers", { params: { search, limit: 100 } }).then(({ data }) => setItems(data.data)).catch(() => toast("Could not load subscribers", "error")), [search, toast]); useEffect(() => { load(); }, [load]); const status = async (item) => { try { await api.put(`/cms/subscribers/${item._id}`, { name: item.name, status: item.status === "subscribed" ? "unsubscribed" : "subscribed" }); toast("Subscriber updated"); load(); } catch { toast("Could not update subscriber", "error"); } }; return <><header className="mb-7"><h2 className="text-2xl font-black">Newsletter</h2><p className="mt-1 text-sm text-slate-500">Review newsletter subscriber status.</p></header><label className="relative mb-5 block max-w-md"><FiSearch className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search subscribers" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 text-sm"/></label><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Email</th><th>Joined</th><th className="px-5">Status</th></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item._id}><td className="px-5 py-4 font-medium">{item.email}</td><td>{date(item.createdAt)}</td><td className="px-5"><button onClick={() => status(item)} className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status === "subscribed" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{item.status}</button></td></tr>)}</tbody></table></div></>;
}
