import mongoose from "mongoose";

const siteSettingsSchema = new mongoose.Schema(
  {
    key: { type: String, default: "site", unique: true },
    siteName: { type: String, default: "SoleVerse" },
    logo: { type: String, default: "" },
    logoPublicId: { type: String, default: "" },
    footerText: { type: String, default: "" },
    seo: { title: String, description: String, keywords: String },
    social: {
      instagram: String,
      twitter: String,
      facebook: String,
      youtube: String,
    },
    homepage: {
      breakingNews: {
        enabled: { type: Boolean, default: true },
        text: { type: String, default: "" },
        headline: { type: String, default: "" },
        link: { type: String, default: "" },
        badge: { type: String, default: "NEW" },
        animation: {
          type: String,
          enum: ["ticker", "static"],
          default: "ticker",
        },
        backgroundColor: { type: String, default: "#050505" },
        textColor: { type: String, default: "#ffffff" },
        speed: { type: Number, default: 28 },
      },
      navigation: {
        transparent: { type: Boolean, default: false },
        sticky: { type: Boolean, default: true },
        backgroundColor: { type: String, default: "#050505" },
        textColor: { type: String, default: "#ffffff" },
        items: {
          type: [
            {
              label: String,
              path: String,
              enabled: { type: Boolean, default: true },
              order: Number,
            },
          ],
          default: [],
        },
      },
      sections: {
        type: [
          {
            id: String,
            enabled: { type: Boolean, default: true },
            order: Number,
            limit: Number,
            title: String,
            subtitle: String,
            buttonText: String,
            buttonUrl: String,
            backgroundColor: String,
            backgroundImage: String,
            padding: String,
            margin: String,
            containerWidth: String,
            borderRadius: String,
            shadow: String,
            animation: String,
            desktopVisible: { type: Boolean, default: true },
            tabletVisible: { type: Boolean, default: true },
            mobileVisible: { type: Boolean, default: true },
            customClass: String,
          },
        ],
        default: [],
      },
      hero: {
        autoPlay: { type: Boolean, default: true },
        sliderSpeed: { type: Number, default: 6000 },
        backgroundImage: { type: String, default: "" },
        overlayColor: { type: String, default: "#050505" },
        overlayOpacity: { type: Number, default: 55 },
        imagePosition: { type: String, default: "right" },
        textAlign: { type: String, default: "left" },
        primaryCtaColor: { type: String, default: "#eee0c9" },
        secondaryCtaColor: { type: String, default: "#ffffff" },
        animation: { type: String, default: "fade" },
      },
      newsletter: {
        enabled: { type: Boolean, default: true },
        title: { type: String, default: "" },
        subtitle: { type: String, default: "" },
        backgroundColor: { type: String, default: "#080808" },
        backgroundImage: { type: String, default: "" },
        sneakerImage: { type: String, default: "" },
        buttonText: { type: String, default: "Subscribe" },
        buttonColor: { type: String, default: "#eee0c9" },
        placeholder: { type: String, default: "Enter your email address" },
        successMessage: { type: String, default: "You’re on the list." },
      },
      trending: {
        mode: { type: String, enum: ["manual", "views"], default: "views" },
        manualIds: { type: [mongoose.Schema.Types.ObjectId], default: [] },
        featuredOnly: { type: Boolean, default: false },
        statusLabel: { type: String, default: "Trending" },
      },
      footer: {
        description: { type: String, default: "" },
        copyright: { type: String, default: "" },
        quickLinks: { type: [{ label: String, path: String }], default: [] },
        categories: { type: [String], default: [] },
        contact: { type: String, default: "" },
      },
    },
  },
  { timestamps: true },
);

export default mongoose.model("SiteSettings", siteSettingsSchema);
