import { useEffect, useState } from "react";
import api from "../../api/axios";
import { useToast } from "../components/Toast";

export default function Settings() {
  const [form, setForm] = useState({ siteName: "", footerText: "", seo: {}, social: {} }); const [logo, setLogo] = useState(null); const [loading, setLoading] = useState(true); const toast = useToast();
  useEffect(() => { api.get("/cms/settings").then(({ data }) => setForm(data.data)).catch(() => toast("Could not load settings", "error")).finally(() => setLoading(false)); }, [toast]);
  const submit = async (event) => { event.preventDefault(); const body = new FormData(); body.append("siteName", form.siteName || ""); body.append("footerText", form.footerText || ""); body.append("seo", JSON.stringify(form.seo || {})); body.append("social", JSON.stringify(form.social || {})); if (logo) body.append("logo", logo); try { const { data } = await api.put("/cms/settings", body); setForm(data.data); setLogo(null); toast("Settings saved"); } catch (error) { toast(error.response?.data?.message || "Could not save settings", "error"); } };
  if (loading) return <div className="py-16 text-center text-slate-500">Loading settings…</div>;
  return <form onSubmit={submit} className="max-w-3xl"><header className="mb-7"><h2 className="text-2xl font-black">Site Settings</h2><p className="mt-1 text-sm text-slate-500">Manage brand, footer, SEO, and social links.</p></header><div className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5"><label className="block text-sm font-medium">Site name<input value={form.siteName || ""} onChange={(e) => setForm({...form,siteName:e.target.value})} className="field"/></label><label className="block text-sm font-medium">Footer text<textarea value={form.footerText || ""} onChange={(e) => setForm({...form,footerText:e.target.value})} className="field" rows="3"/></label><label className="block text-sm font-medium">Logo<input type="file" accept="image/*" onChange={(e) => setLogo(e.target.files[0])} className="field"/></label><label className="block text-sm font-medium">SEO title<input value={form.seo?.title || ""} onChange={(e) => setForm({...form,seo:{...form.seo,title:e.target.value}})} className="field"/></label><label className="block text-sm font-medium">SEO description<textarea value={form.seo?.description || ""} onChange={(e) => setForm({...form,seo:{...form.seo,description:e.target.value}})} className="field" rows="3"/></label><div className="grid gap-4 sm:grid-cols-2">{["instagram", "twitter", "facebook", "youtube"].map((network) => <label key={network} className="block text-sm font-medium capitalize">{network}<input value={form.social?.[network] || ""} onChange={(e) => setForm({...form,social:{...form.social,[network]:e.target.value}})} className="field"/></label>)}</div><button className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Save settings</button></div></form>;
}
