export const SEED_SOURCE = "soleverse-demo";

// Verified Cloudinary URLs already present in the project database/media
// library. Reused to avoid downloading images or introducing broken URLs.
const IMAGES = {
  jordan: [
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786172592/soleverse/release/gfcdcrfw2uns1rnnsylc.webp",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786173644/soleverse/release/h5gqugobayl5wis9mxms.jpg",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786173868/soleverse/release/trx8bxryzz2cemtis6xk.webp",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1785217916/soleverse/home/y7dhve6pdu86kjwzzcwz.png",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786172955/soleverse/media/rmdw4qjobqdn6aucgraz.webp",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786172981/soleverse/media/xghuyg60bmfvuvbhfamp.png",
  ],
  nike: [
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786174962/soleverse/review/sdechdeddybh8oh4gz0r.jpg",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786179911/soleverse/calendar/fhe5ogq6ueslmygyrf8g.jpg",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786180984/soleverse/deal/ylabuayw9n2hogusnzux.jpg",
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786176503/soleverse/brand/zlx5wl3kjhntiq9adk9v.jpg",
  ],
  guide: [
    "https://res.cloudinary.com/gwyaachx/image/upload/v1786177949/soleverse/guide/riyz18imsgb5zso026um.jpg",
  ],
};

const pick = (pool, index) => pool[index % pool.length];
const generic = [...IMAGES.jordan, ...IMAGES.nike];

const imageFor = (brand, index) => {
  const key = brand?.toLowerCase();
  if (key === "jordan") return pick(IMAGES.jordan, index);
  if (key === "nike") return pick(IMAGES.nike, index);
  return pick(generic, index);
};

const seo = (title, description) => ({
  metaTitle: title,
  metaDescription: description,
});

export const DEMO_BRANDS = [
  {
    slug: "jordan",
    name: "Jordan",
    featured: true,
    metadata: {
      country: "United States",
      founded: 1984,
      founder: "Michael Jordan",
      headquarters: "Beaverton, Oregon, United States",
      website: "https://www.jordan.com",
      shortDescription:
        "Jordan Brand is Nike's premium basketball and lifestyle division, built around Michael Jordan's legacy and an evergreen catalog of iconic silhouettes.",
      history:
        "Jordan Brand launched in 1984 with the Air Jordan 1, designed by Peter Moore. The silhouette was famously banned by the NBA, giving it instant cultural gravity.\n\nThrough the 1980s and 1990s, Tinker Hatfield designed a series of groundbreaking models worn by Michael Jordan across six championships. The brand grew from performance basketball into a global lifestyle powerhouse.\n\nToday Jordan Brand continues to release retro and modern silhouettes that command both the court and the street.",
      mission:
        "Jordan Brand exists to celebrate Michael Jordan's legacy and to bring his competitive spirit to basketball, fashion, and street culture around the world.",
      innovation: "Jordan Brand is known for Flight Plate, Zoom Air cushioning, and premium craftsmanship on both performance and retro lines.\n\nRetro engineering keeps classics true to their original form while modern models push lightweight performance forward.",
      legacy:
        "The Air Jordan line is the most successful sneaker franchise in history, with releases routinely selling out and defining global sneaker culture.",
      popularTechnologies: "Zoom Air\nFlight Plate\nAir-Sole",
      signatureModels: "Air Jordan 1\nAir Jordan 3\nAir Jordan 4\nAir Jordan 11\nAir Jordan 12",
      athletes: "Michael Jordan\nCarmelo Anthony\nLuka Dončić\nChris Paul",
      ...seo(
        "Jordan Sneakers, Releases & Reviews | SoleVerse",
        "Explore Jordan Brand sneakers on SoleVerse, including the latest Air Jordan releases, reviews, retro models, and cultural history.",
      ),
    },
  },
  {
    slug: "adidas",
    name: "adidas",
    featured: true,
    metadata: {
      country: "Germany",
      founded: 1949,
      founder: "Adi Dassler",
      headquarters: "Herzogenaurach, Germany",
      website: "https://www.adidas.com",
      shortDescription:
        "adidas is a German sportswear giant famous for the Three Stripes, classic silhouettes like the Samba and Gazelle, and BOOST cushioning.",
      history:
        "adidas was founded in 1949 by Adi Dassler in Herzogenaurach, Germany. The Three Stripes quickly became a symbol of athletic ambition.\n\nOver the decades adidas built a storied performance catalog while its lifestyle line exploded through football, tennis, and skate culture. Models like the Samba, Gazelle, Superstar, and Stan Smith became cultural staples.\n\nModern innovations such as BOOST and Primeknit keep the brand at the forefront of performance footwear.",
      mission: "adidas' mission is to be the best sports brand in the world, creating products that help athletes perform while advancing sustainability.",
      innovation: "adidas is known for BOOST foam, Primeknit uppers, Continental rubber outsoles, and the FourD printed midsole concept.\n\nThe Samba's timeless gum sole and clean lines remain a masterclass in design restraint.",
      legacy: "The Samba, Gazelle, and Superstar are among the most culturally significant sneakers ever made, spanning football terraces, hip-hop, and runways.",
      popularTechnologies: "BOOST\nPrimeknit\nContinental Rubber",
      signatureModels: "Samba\nGazelle\nSuperstar\nStan Smith\nCampus",
      athletes: "Lionel Messi\nDerrick Rose\nTrae Young\nSnoop Dogg",
      ...seo(
        "adidas Sneakers, Releases & Reviews | SoleVerse",
        "Explore adidas sneakers on SoleVerse, including the latest Samba and Gazelle releases, reviews, technology, and brand history.",
      ),
    },
  },
  {
    slug: "new-balance",
    name: "New Balance",
    featured: true,
    metadata: {
      country: "United States",
      founded: 1906,
      founder: "William J. Riley",
      headquarters: "Boston, Massachusetts, United States",
      website: "https://www.newbalance.com",
      shortDescription:
        "New Balance is the Boston-born brand celebrated for premium craftsmanship, Made in USA heritage, and the 990 family of running legends.",
      history:
        "New Balance began in 1906 as the New Balance Arch Support Company in Boston. The brand pivoted to athletic footwear in the 1960s and gained fame through the 990 series.\n\nThe 990 launched in 1982 as the first premium-priced running shoe and became a wardrobe staple for dads, designers, and celebrities alike.\n\nToday New Balance balances performance running with a lifestyle boom driven by models like the 9060, 2002R, and the ever-popular 990v6.",
      mission: "New Balance is committed to craftsmanship, comfort, and domestic manufacturing, proving that quality and style can coexist.",
      innovation: "New Balance is known for ENCAP, ABZORB, FuelCell foam, and its Made in USA manufacturing programs.\n\nThe 990 series demonstrates a relentless focus on comfort and build quality over flashy trends.",
      legacy: "The 990 family is arguably the most enduring premium sneaker line ever created, beloved by runners and fashion circles in equal measure.",
      popularTechnologies: "FuelCell\nENCAP\nABZORB",
      signatureModels: "990v6\n9060\n2002R\n550\nMade in USA 990v3",
      athletes: "Kawhi Leonard\nCoco Gauff",
      ...seo(
        "New Balance Sneakers, Releases & Reviews | SoleVerse",
        "Explore New Balance sneakers on SoleVerse, including the 990 series, 9060, releases, reviews, and brand heritage.",
      ),
    },
  },
  {
    slug: "asics",
    name: "ASICS",
    featured: true,
    metadata: {
      country: "Japan",
      founded: 1949,
      founder: "Kihachiro Onitsuka",
      headquarters: "Kobe, Hyogo, Japan",
      website: "https://www.asics.com",
      shortDescription:
        "ASICS is the Japanese performance giant behind Gel cushioning and running legends like the Gel-Kayano and Gel-NYC.",
      history:
        "ASICS was founded in 1949 by Kihachiro Onitsuka in Kobe, Japan. The name stands for Anima Sana In Corpore Sano, meaning a sound mind in a sound body.\n\nThrough running and court sports, ASICS built a reputation for technical excellence. The Gel-Kayano debuted in 1993 and became the world's most trusted stability trainer.\n\nThe brand's retro running archive has recently exploded in popularity, with models like the Gel-Kayano 14 and Gel-NYC dominating the fashion sneaker scene.",
      mission: "ASICS exists to promote health and wellbeing through sport, helping people run and live a sound life in a sound body.",
      innovation: "ASICS pioneered Gel cushioning, the FLYTEFOAM midsole, and GEL technology across performance and lifestyle silhouettes.\n\nThe Gel-Kayano 14's chunky metallic panels defined the Y2K runner aesthetic.",
      legacy: "ASICS bridges elite running performance with retro nostalgia better than almost any brand in the industry.",
      popularTechnologies: "Gel\nFLYTEFOAM\nTrusstic",
      signatureModels: "Gel-Kayano 14\nGel-NYC\nGT-2000\nGel-1130",
      athletes: "Tommie Smith\nBrigid Kosgei",
      ...seo(
        "ASICS Sneakers, Releases & Reviews | SoleVerse",
        "Explore ASICS sneakers on SoleVerse, including Gel-Kayano releases, reviews, running technology, and brand history.",
      ),
    },
  },
  {
    slug: "puma",
    name: "Puma",
    featured: false,
    metadata: {
      country: "Germany",
      founded: 1948,
      founder: "Rudolf Dassler",
      headquarters: "Herzogenaurach, Germany",
      website: "https://us.puma.com",
      shortDescription:
        "Puma is the German sportswear brand known for the Suede, the Speedcat, and a deep connection to football, motorsport, and street culture.",
      history:
        "Puma was founded in 1948 by Rudolf Dassler, brother of adidas founder Adi Dassler, in Herzogenaurach, Germany.\n\nThe Suede debuted in 1968 and became an icon of hip-hop and B-boy culture. The Speedcat found fame on Formula 1 pit lanes.\n\nRecently the Speedcat has made a fashion comeback, while Puma continues to grow in basketball through LaMelo Ball's MB series.",
      mission: "Puma is Forever Faster, creating performance sportswear that merges sport, motorsport, and street culture.",
      innovation: "Puma is known for Nitro foam cushioning, the suede construction of its classic silhouettes, and strong motorsport and streetwear collaborations.",
      legacy: "The Puma Suede is one of the most important sneakers in hip-hop history, and the Speedcat is the definitive motorsport lifestyle shoe.",
      popularTechnologies: "Nitro Foam\nSuede Construction",
      signatureModels: "Suede\nSpeedcat\nMB.03\nPalermo",
      athletes: "LaMelo Ball\nUsain Bolt\nNeymar",
      ...seo(
        "Puma Sneakers, Releases & Reviews | SoleVerse",
        "Explore Puma sneakers on SoleVerse, including the Suede, Speedcat, MB series, releases, reviews, and brand history.",
      ),
    },
  },
  {
    slug: "converse",
    name: "Converse",
    featured: false,
    metadata: {
      country: "United States",
      founded: 1908,
      founder: "Marquis Mills Converse",
      headquarters: "Boston, Massachusetts, United States",
      website: "https://www.converse.com",
      shortDescription:
        "Converse is the American icon behind the Chuck Taylor All Star and Chuck 70, sneakers that defined basketball, rock, and skate culture for a century.",
      history:
        "Converse was founded in 1908 by Marquis Mills Converse in Malden, Massachusetts. The All Star basketball shoe arrived in 1917, with Chuck Taylor joining as a salesman and player advocate in 1921.\n\nThe Chuck Taylor All Star became the best-selling sneaker in history, crossing from the court into rock and roll, punk, and street style.\n\nToday the premium Chuck 70 and a rotating slate of collaborations keep the canvas classic essential.",
      mission: "Converse exists to champion the spirit of originality, making the All Star a canvas for creativity and self-expression.",
      innovation: "Converse has evolved the canvas sneaker with modern cushioning in the Chuck 70 and Cons lines while honoring the classic All Star DNA.",
      legacy: "The Chuck Taylor All Star has been worn by basketball pioneers, rock icons, and artists for over a century, making it the most iconic sneaker in history.",
      popularTechnologies: "Lugged Sole\nCanvas Upper\nModern Comfort",
      signatureModels: "Chuck 70\nChuck Taylor All Star\nCons\nRun Star Motion",
      athletes: "Charles Barkley\nBlake Griffin\nKelly Oubre Jr.",
      ...seo(
        "Converse Sneakers, Releases & Reviews | SoleVerse",
        "Explore Converse sneakers on SoleVerse, including the Chuck 70 and All Star, releases, reviews, and brand history.",
      ),
    },
  },
  {
    slug: "vans",
    name: "Vans",
    featured: false,
    metadata: {
      country: "United States",
      founded: 1966,
      founder: "Paul Van Doren",
      headquarters: "Cypress, California, United States",
      website: "https://www.vans.com",
      shortDescription:
        "Vans is the California skate brand known for the Old Skool, Sk8-Hi, and the signature checkerboard pattern that became streetwear shorthand.",
      history:
        "Vans opened its first store in Anaheim, California in 1966. The slip-on style 44 arrived in 1977 and, paired with a checkerboard pattern, became a pop-culture phenomenon.\n\nThe Old Skool and Sk8-Hi defined skateboarding footwear, with the waffle outsole providing legendary grip.\n\nVans remains the default choice for skaters, punks, and streetwear heads alike.",
      mission: "Vans is Off The Wall, championing action sports, street culture, and creative expression.",
      innovation: "Vans is known for the waffle outsole, the checkerboard print, and durable canvas and suede constructions built for skateboarding.",
      legacy: "The checkerboard slip-on is one of the most recognizable sneaker patterns ever created, cementing Vans' place in skate and pop culture.",
      popularTechnologies: "Waffle Outsole\nComfyCush\nPopCush",
      signatureModels: "Old Skool\nSk8-Hi\nAuthentic\nKnu Skool\nCheckerboard Slip-On",
      athletes: "Anthony Van Engelen\nChima Ferguson",
      ...seo(
        "Vans Sneakers, Releases & Reviews | SoleVerse",
        "Explore Vans sneakers on SoleVerse, including the Old Skool, Sk8-Hi, releases, reviews, and skate culture history.",
      ),
    },
  },
].map(({ slug, name, featured, metadata }) => ({
  type: "brand",
  slug,
  title: name,
  category: "Sneakers",
  summary: metadata.shortDescription,
  content: `${metadata.history}\n\n${metadata.legacy}\n\n${metadata.innovation}`,
  image: "",
  featured,
  status: "published",
  metadata,
}));

export const DEMO_RELEASES = [
  {
    slug: "nike-air-force-1-low-triple-white",
    title: "Nike Air Force 1 Low \"Triple White\"",
    category: "Nike",
    featured: true,
    metadata: {
      brand: "Nike",
      model: "Air Force 1 Low",
      colorway: "White / White / White",
      sku: "CW2288-111",
      releaseDate: "2026-08-15T06:30:00.000Z",
      retailPrice: 115,
      currency: "USD",
      region: "Worldwide",
      designer: "Bruce Kilgore",
      materials: "Full-Grain Leather",
      technology: "Air-Sole Unit",
      sizes: "US 4-15",
      styleCode: "CW2288-111",
    },
  },
  {
    slug: "adidas-samba-og-core-black",
    title: "adidas Samba OG \"Core Black\"",
    category: "adidas",
    featured: false,
    metadata: {
      brand: "adidas",
      model: "Samba OG",
      colorway: "Core Black / Gum 4",
      sku: "ID0478",
      releaseDate: "2026-08-22T06:30:00.000Z",
      retailPrice: 100,
      currency: "USD",
      region: "Worldwide",
      designer: "adidas Heritage",
      materials: "Full-Grain Leather & Suede",
      technology: "Classic Gum Rubber",
      sizes: "US 4-14",
      styleCode: "ID0478",
    },
  },
  {
    slug: "puma-speedcat-og-red",
    title: "Puma Speedcat OG \"Red\"",
    category: "Puma",
    featured: false,
    metadata: {
      brand: "Puma",
      model: "Speedcat OG",
      colorway: "Puma Red / White",
      sku: "306204-01",
      releaseDate: "2026-08-28T06:30:00.000Z",
      retailPrice: 90,
      currency: "USD",
      region: "Europe",
      designer: "Puma Motorsport",
      materials: "Suede & Leather",
      technology: "Heritage Racing Sole",
      sizes: "US 4-13",
      styleCode: "306204-01",
    },
  },
  {
    slug: "nike-dunk-low-panda",
    title: "Nike Dunk Low \"Panda\"",
    category: "Nike",
    featured: false,
    metadata: {
      brand: "Nike",
      model: "Dunk Low",
      colorway: "White / Black",
      sku: "DD1391-100",
      releaseDate: "2026-08-29T06:30:00.000Z",
      retailPrice: 115,
      currency: "USD",
      region: "Worldwide",
      designer: "Peter Moore",
      materials: "Full-Grain Leather",
      technology: "Classic Cupsole",
      sizes: "US 4-14",
      styleCode: "DD1391-100",
    },
  },
  {
    slug: "new-balance-990v6-grey-day",
    title: "New Balance 990v6 \"Grey Day\"",
    category: "New Balance",
    featured: false,
    metadata: {
      brand: "New Balance",
      model: "990v6",
      colorway: "Grey / White",
      sku: "U990GL6",
      releaseDate: "2026-09-05T06:30:00.000Z",
      retailPrice: 200,
      currency: "USD",
      region: "Worldwide",
      designer: "New Balance MADE",
      materials: "Suede, Mesh & Leather",
      technology: "FuelCell Foam",
      sizes: "US 4-14",
      styleCode: "U990GL6",
    },
  },
  {
    slug: "asics-gel-kayano-14-silver-blue",
    title: "ASICS Gel-Kayano 14 \"Silver Blue\"",
    category: "ASICS",
    featured: false,
    metadata: {
      brand: "ASICS",
      model: "Gel-Kayano 14",
      colorway: "Silver / Blue",
      sku: "1201A763-100",
      releaseDate: "2026-09-18T06:30:00.000Z",
      retailPrice: 160,
      currency: "USD",
      region: "Asia",
      designer: "ASICS Sportstyle",
      materials: "Mesh & Synthetic Leather",
      technology: "Gel Cushioning",
      sizes: "US 4-13",
      styleCode: "1201A763-100",
    },
  },
  {
    slug: "vans-old-skool-checkerboard",
    title: "Vans Old Skool \"Checkerboard\"",
    category: "Vans",
    featured: false,
    metadata: {
      brand: "Vans",
      model: "Old Skool",
      colorway: "Black / White",
      sku: "VN000D3HY28",
      releaseDate: "2026-09-25T06:30:00.000Z",
      retailPrice: 75,
      currency: "USD",
      region: "Worldwide",
      designer: "Paul Van Doren",
      materials: "Suede & Canvas",
      technology: "Waffle Outsole",
      sizes: "US 3.5-13",
      styleCode: "VN000D3HY28",
    },
  },
  {
    slug: "converse-chuck-70-tri-panel",
    title: "Converse Chuck 70 \"Tri-Panel\"",
    category: "Converse",
    featured: false,
    metadata: {
      brand: "Converse",
      model: "Chuck 70",
      colorway: "White / Black / Gum",
      sku: "A00559C",
      releaseDate: "2026-10-02T06:30:00.000Z",
      retailPrice: 90,
      currency: "USD",
      region: "Europe",
      designer: "Converse Design Team",
      materials: "Canvas",
      technology: "OrthoLite Cushioning",
      sizes: "US 4-13",
      styleCode: "A00559C",
    },
  },
  {
    slug: "jordan-3-white-cement-reimagined",
    title: "Air Jordan 3 \"White Cement Reimagined\"",
    category: "Jordan",
    featured: true,
    metadata: {
      brand: "Jordan",
      model: "Air Jordan 3",
      colorway: "White / Cement Grey",
      sku: "DN3707-100",
      releaseDate: "2026-10-16T06:30:00.000Z",
      retailPrice: 200,
      currency: "USD",
      region: "Worldwide",
      designer: "Tinker Hatfield",
      materials: "Premium Leather & Elephant Print",
      technology: "Air-Sole Unit",
      sizes: "US 4-15",
      styleCode: "DN3707-100",
    },
  },
  {
    slug: "jordan-11-bred",
    title: "Air Jordan 11 \"Bred\"",
    category: "Jordan",
    featured: false,
    metadata: {
      brand: "Jordan",
      model: "Air Jordan 11",
      colorway: "Black / Varsity Red",
      sku: "378037-061",
      releaseDate: "2026-12-11T06:30:00.000Z",
      retailPrice: 230,
      currency: "USD",
      region: "Worldwide",
      designer: "Tinker Hatfield",
      materials: "Patent Leather & Mesh",
      technology: "Full-Length Air-Sole",
      sizes: "US 4-15",
      styleCode: "378037-061",
    },
  },
].map(({ slug, title, category, featured, metadata }, index) => ({
  type: "release",
  slug,
  title,
  category,
  summary: `${metadata.brand} ${metadata.model} in the ${metadata.colorway} colorway. Retails at $${metadata.retailPrice} and releases ${new Date(metadata.releaseDate).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}.`,
  content: `The ${metadata.model} from ${metadata.brand} lands in a ${metadata.colorway} colorway, a release built on premium ${metadata.materials} with ${metadata.technology} tech.\n\nThis drop is available in sizes ${metadata.sizes} across the ${metadata.region} market. Keep an eye on the release calendar for retailer and raffle details.\n\nA worthy addition to any rotation, the ${metadata.model} continues ${metadata.brand}'s legacy of blending performance, design, and cultural relevance.`,
  image: imageFor(metadata.brand, index),
  featured,
  status: "published",
  metadata,
}));

export const DEMO_REVIEWS = [
  {
    slug: "adidas-samba-og-review",
    title: "adidas Samba OG Review: The Timeless Terrace Classic",
    category: "Sneakers",
    featured: true,
    metadata: {
      brand: "adidas",
      model: "Samba OG",
      colorway: "Core Black / Gum 4",
      reviewer: "SoleVerse Editorial Team",
      reviewDate: "2026-08-08T06:30:00.000Z",
      comfort: 8.2,
      quality: 8.9,
      materials: 8.6,
      fit: 8.4,
      durability: 8.7,
      traction: 8.3,
      breathability: 7.5,
      value: 8.8,
      retailPrice: 100,
      weight: "Approx. 11.5 oz (326 g)",
      bestFor: "Street style, everyday casual wear, terrace culture",
      quickSummary:
        "The adidas Samba OG is a heritage silhouette that pairs razor-thin profile, premium leather, and an iconic gum sole into one of the most wearable sneakers ever made.",
      pros: "Premium full-grain leather upper\nTimeless silhouette that pairs with everything\nExcellent build quality for the price\nComfortable gum outsole with strong grip\nWidely available at a fair price",
      cons: "Thin sole offers limited cushioning for all-day wear\nNarrow fit runs slightly long\nNot suitable for wet weather due to suede accents",
      verdict:
        "The Samba OG is proof that a sneaker does not need radical technology to be great. Its heritage design, quality materials, and endless versatility make it a must-have for any rotation.\n\nIf you prioritize plush cushioning or arch support, the thin sole will leave you wanting more. But for everyday style, the Samba is an easy recommendation.",
    },
  },
  {
    slug: "new-balance-990v6-review",
    title: "New Balance 990v6 Review: Premium Comfort, Refined Design",
    category: "Sneakers",
    featured: true,
    metadata: {
      brand: "New Balance",
      model: "990v6",
      colorway: "Grey / White",
      reviewer: "SoleVerse Editorial Team",
      reviewDate: "2026-08-10T06:30:00.000Z",
      comfort: 9.4,
      quality: 9.1,
      materials: 8.9,
      fit: 8.8,
      durability: 8.9,
      traction: 8.2,
      breathability: 8.4,
      value: 8.1,
      retailPrice: 200,
      weight: "Approx. 12 oz (340 g)",
      bestFor: "All-day wear, travel, standing and walking",
      quickSummary:
        "The New Balance 990v6 delivers best-in-class comfort, premium Made in USA craftsmanship, and a dad-core silhouette that has become a global style staple.",
      pros: "Outstanding FuelCell cushioning\nPremium Made in USA build quality\nVersatile grey colorway\nGreat arch support for long days\nTimeless design that ages well",
      cons: "Premium price point\nRuns slightly narrow for wide feet\nHeavier than modern running shoes",
      verdict:
        "The 990v6 is the gold standard for premium everyday sneakers. New Balance's FuelCell foam makes it one of the most comfortable shoes on the market, and the craftsmanship is exceptional.\n\nIt is an investment, but for comfort-first buyers, the 990v6 more than earns its keep.",
    },
  },
  {
    slug: "asics-gel-kayano-14-review",
    title: "ASICS Gel-Kayano 14 Review: Retro Runner Meets Modern Comfort",
    category: "Sneakers",
    featured: false,
    metadata: {
      brand: "ASICS",
      model: "Gel-Kayano 14",
      colorway: "Silver / Blue",
      reviewer: "SoleVerse Editorial Team",
      reviewDate: "2026-08-12T06:30:00.000Z",
      comfort: 8.8,
      quality: 8.6,
      materials: 8.3,
      fit: 8.5,
      durability: 8.6,
      traction: 8.1,
      breathability: 8.2,
      value: 8.4,
      retailPrice: 160,
      weight: "Approx. 11 oz (312 g)",
      bestFor: "Retro running style, everyday comfort, Y2K looks",
      quickSummary:
        "The ASICS Gel-Kayano 14 revives a 2000s stability runner with chunky metallic panels and surprisingly modern Gel cushioning.",
      pros: "Distinctive Y2K aesthetic\nGel cushioning is genuinely comfortable\nGreat colorways with metallic accents\nExcellent ankle support\nStrong build quality",
      cons: "Chunky silhouette not for everyone\nRuns slightly small\nLimited colorway availability at retail",
      verdict:
        "The Gel-Kayano 14 is a fantastic retro runner that stands out in a sea of chunky sneakers. Its Gel cushioning delivers real comfort while the design celebrates 2000s running heritage.\n\nIf you love Y2K style and want a shoe that pairs performance DNA with fashion, this is a strong pick.",
    },
  },
  {
    slug: "jordan-3-white-cement-reimagined-review",
    title: "Air Jordan 3 White Cement Review: The Elephant Print Icon",
    category: "Sneakers",
    featured: false,
    metadata: {
      brand: "Jordan",
      model: "Air Jordan 3",
      colorway: "White / Cement Grey",
      reviewer: "SoleVerse Editorial Team",
      reviewDate: "2026-08-14T06:30:00.000Z",
      comfort: 8.5,
      quality: 9.0,
      materials: 8.8,
      fit: 8.6,
      durability: 8.4,
      traction: 8.3,
      breathability: 7.8,
      value: 8.2,
      retailPrice: 200,
      weight: "Approx. 14 oz (397 g)",
      bestFor: "Retro basketball style, streetwear, collectors",
      quickSummary:
        "The Air Jordan 3 White Cement combines Tinker Hatfield's elephant print design with premium leather and legendary Air cushioning.",
      pros: "Iconic design with elephant print accents\nPremium leather materials\nComfortable Air-Sole cushioning\nStrong cultural and collector value\nGreat colorway versatility",
      cons: "Higher resale price on popular sizes\nWarm due to leather upper\nSqueaks can develop over time",
      verdict:
        "The Air Jordan 3 White Cement is a cornerstone of sneaker history. Tinker Hatfield's design remains timeless, and the premium materials hold up beautifully.\n\nFor collectors and streetwear fans, the AJ3 is an essential piece of the rotation.",
    },
  },
  {
    slug: "nike-air-force-1-low-review",
    title: "Nike Air Force 1 Review: The Everyday Icon That Refuses to Age",
    category: "Sneakers",
    featured: false,
    metadata: {
      brand: "Nike",
      model: "Air Force 1 Low",
      colorway: "White / White",
      reviewer: "SoleVerse Editorial Team",
      reviewDate: "2026-08-16T06:30:00.000Z",
      comfort: 8.3,
      quality: 8.4,
      materials: 8.2,
      fit: 8.5,
      durability: 8.6,
      traction: 8.2,
      breathability: 7.6,
      value: 8.7,
      retailPrice: 115,
      weight: "Approx. 15 oz (425 g)",
      bestFor: "Everyday wear, street style, versatile casual rotation",
      quickSummary:
        "The Nike Air Force 1 Low remains the definitive clean white sneaker, offering classic proportions, sturdy leather, and unmatched cultural ubiquity.",
      pros: "Timeless silhouette\nSturdy full-grain leather\nExcellent value for the price\nPairs with almost anything\nHuge size availability",
      cons: "Heavy compared with modern lifestyle shoes\nCreases easily on the toe box\nWarm for summer wear",
      verdict:
        "The Air Force 1 needs no introduction. It is the most versatile white sneaker in history and a reliable everyday choice.\n\nIt is heavier and warmer than newer options, but its classic look and durability make it an easy recommendation.",
    },
  },
  {
    slug: "puma-suede-review",
    title: "Puma Suede Review: The Original Hip-Hop Sneaker",
    category: "Sneakers",
    featured: true,
    metadata: {
      brand: "Puma",
      model: "Suede",
      colorway: "Puma Black / White",
      reviewer: "SoleVerse Editorial Team",
      reviewDate: "2026-08-18T06:30:00.000Z",
      comfort: 7.8,
      quality: 8.3,
      materials: 8.1,
      fit: 8.0,
      durability: 7.9,
      traction: 8.0,
      breathability: 7.4,
      value: 8.6,
      retailPrice: 85,
      weight: "Approx. 10.5 oz (298 g)",
      bestFor: "Street style, skate culture, hip-hop heritage",
      quickSummary:
        "The Puma Suede is a legendary silhouette that blends soft suede, clean lines, and cultural history into a wallet-friendly essential.",
      pros: "Rich suede construction\nAffordable price point\nRich cultural heritage\nLightweight and flexible\nPairs well with denim and streetwear",
      cons: "Minimal cushioning\nSuede needs care in wet weather\nRuns narrow for wider feet",
      verdict:
        "The Puma Suede is an affordable piece of sneaker history. It is light, flexible, and packed with street culture credibility.\n\nIf you prioritize cushioning, look elsewhere, but for style on a budget, the Suede is hard to beat.",
    },
  },
].map(({ slug, title, category, featured, metadata }, index) => ({
  type: "review",
  slug,
  title,
  category,
  summary: metadata.quickSummary,
  content: `${metadata.quickSummary}\n\n${metadata.verdict}\n\nRetail price: $${metadata.retailPrice}. Weight: ${metadata.weight}. Best for: ${metadata.bestFor}.`,
  image: imageFor(metadata.brand, index),
  featured,
  status: "published",
  metadata,
}));

export const DEMO_GUIDES = [
  {
    slug: "best-everyday-sneakers",
    title: "Best Everyday Sneakers: The Complete Guide",
    category: "Buying Guides",
    featured: true,
    metadata: {
      category: "Buying Guides",
      guideType: "Buying",
      author: "SoleVerse Editorial Team",
      publishedDate: "2026-08-08T06:30:00.000Z",
      readingTime: "7 min read",
      brand: "Nike",
      model: "Air Max Dn",
      colorway: "Black / Anthracite",
      productCategory: "Lifestyle",
      difficulty: "Beginner",
      bestFor: "Anyone looking for a comfortable, versatile everyday sneaker",
      keyTakeaways:
        "Comfort should be the top priority for daily wear\nLook for breathable materials for all-day use\nNeutral colorways offer the most versatility\nA cushioned midsole reduces fatigue on long days\nDurability matters when you wear a shoe every day",
      recommendedModels:
        "Nike Air Max Dn\nNew Balance 990v6\nadidas Samba OG\nASICS Gel-Kayano 14\nConverse Chuck 70",
      relatedTopics:
        "Sneaker sizing\nSneaker comfort\nSneaker materials\nEveryday sneakers\nSneaker buying tips",
      metaTitle: "Best Everyday Sneakers 2026 | SoleVerse",
      metaDescription:
        "The best everyday sneakers for comfort, style, and durability — reviewed and ranked by the SoleVerse editorial team.",
      ogTitle: "Best Everyday Sneakers 2026",
      ogDescription: "Our picks for the most comfortable, versatile everyday sneakers of 2026.",
    },
  },
  {
    slug: "best-running-sneakers-for-beginners",
    title: "Best Running Sneakers for Beginners",
    category: "Buying Guides",
    guideType: "Buying",
    featured: false,
    metadata: {
      category: "Buying Guides",
      guideType: "Buying",
      author: "SoleVerse Editorial Team",
      publishedDate: "2026-08-10T06:30:00.000Z",
      readingTime: "6 min read",
      brand: "Nike",
      model: "Pegasus 41",
      colorway: "Black / White",
      productCategory: "Running",
      difficulty: "Beginner",
      bestFor: "New runners building their first daily rotation",
      keyTakeaways:
        "Start with a neutral daily trainer\nPrioritize cushioning and a forgiving ride\nBuy true to size with a thumb-width of toe room\nRotate two pairs to extend shoe life\nReplace running shoes every 300-500 miles",
      recommendedModels:
        "Nike Pegasus 41\nNew Balance Fresh Foam 1080v14\nASICS Gel-Nimbus 27\nadidas Ultraboost 5\nPuma Velocity Nitro 3",
      relatedTopics:
        "Running shoes\nSneaker sizing\nRunning technique\nCushioning technology\nBuying guides",
      metaTitle: "Best Running Sneakers for Beginners | SoleVerse",
      metaDescription:
        "The best running sneakers for beginner runners, chosen for cushioning, stability, and easy, forgiving rides.",
      ogTitle: "Best Running Sneakers for Beginners",
      ogDescription: "A beginner-friendly guide to choosing your first running sneaker.",
    },
  },
  {
    slug: "how-to-choose-the-right-sneaker-size",
    title: "How to Choose the Right Sneaker Size",
    category: "Beginner Basics",
    featured: false,
    metadata: {
      category: "Beginner Basics",
      guideType: "Beginner",
      author: "SoleVerse Editorial Team",
      publishedDate: "2026-08-12T06:30:00.000Z",
      readingTime: "5 min read",
      brand: "",
      model: "",
      colorway: "",
      productCategory: "Lifestyle",
      difficulty: "Beginner",
      bestFor: "Anyone confused about which sneaker size to buy",
      keyTakeaways:
        "Measure your feet at the end of the day when they are largest\nLeave a thumb-width of space at the toe\nDifferent brands fit differently, so check sizing guides\nWide and narrow footers should seek brand-specific fits\nTry before you buy when possible",
      recommendedModels:
        "New Balance 990v6\nASICS Gel-Kayano 14\nadidas Samba OG\nNike Air Force 1\nConverse Chuck 70",
      relatedTopics:
        "Sneaker sizing\nFit guide\nSneaker buying tips\nWide feet\nFoot measurement",
      metaTitle: "How to Choose the Right Sneaker Size | SoleVerse",
      metaDescription:
        "Learn how to choose the right sneaker size with our practical fit guide covering measurement, brands, and width.",
      ogTitle: "How to Choose the Right Sneaker Size",
      ogDescription: "A practical guide to getting your sneaker size right every time.",
    },
  },
  {
    slug: "best-sneakers-under-150",
    title: "Best Sneakers Under $150: Great Kicks, Smart Spending",
    category: "Buying Guides",
    featured: false,
    metadata: {
      category: "Buying Guides",
      guideType: "Buying",
      author: "SoleVerse Editorial Team",
      publishedDate: "2026-08-14T06:30:00.000Z",
      readingTime: "6 min read",
      brand: "adidas",
      model: "Samba OG",
      colorway: "Core Black",
      productCategory: "Lifestyle",
      difficulty: "Beginner",
      bestFor: "Budget-conscious buyers wanting style and quality",
      keyTakeaways:
        "Great sneakers exist well below $150\nLook for classic silhouettes that hold their value\nCheck deals and sales before paying retail\nLeather and suede often beat synthetic materials\nVersatile colorways stretch your budget further",
      recommendedModels:
        "adidas Samba OG\nPuma Suede\nConverse Chuck 70\nNike Dunk Low\nVans Old Skool",
      relatedTopics:
        "Budget sneakers\nBest deals\nSneaker value\nEveryday sneakers\nBuying guides",
      metaTitle: "Best Sneakers Under $150 | SoleVerse",
      metaDescription:
        "The best sneakers under $150, balancing style, quality, and value for budget-conscious buyers.",
      ogTitle: "Best Sneakers Under $150",
      ogDescription: "Our favorite sneakers under $150 that don't compromise on style.",
    },
  },
  {
    slug: "best-basketball-sneakers",
    title: "Best Basketball Sneakers: Court Performance Guide",
    category: "Buying Guides",
    featured: false,
    metadata: {
      category: "Buying Guides",
      guideType: "Buying",
      author: "SoleVerse Editorial Team",
      publishedDate: "2026-08-16T06:30:00.000Z",
      readingTime: "7 min read",
      brand: "Jordan",
      model: "Air Jordan 3",
      colorway: "White / Cement",
      productCategory: "Basketball",
      difficulty: "Intermediate",
      bestFor: "Ballers and hoops fans looking for court-ready sneakers",
      keyTakeaways:
        "Look for strong ankle support for lateral movements\nTraction is critical on clean courts\nCushioning protects joints on hard landings\nFit should be snug but not tight\nConsider your playing style before choosing a model",
      recommendedModels:
        "Air Jordan 3\nNike LeBron 21\nadidas Trae Young 3\nPuma MB.03\nNew Balance Kawhi",
      relatedTopics:
        "Basketball sneakers\nAnkle support\nCourt traction\nSneaker cushioning\nBuying guides",
      metaTitle: "Best Basketball Sneakers 2026 | SoleVerse",
      metaDescription:
        "The best basketball sneakers for traction, support, and cushioning, reviewed for players of every style.",
      ogTitle: "Best Basketball Sneakers 2026",
      ogDescription: "A performance guide to the best basketball sneakers of 2026.",
    },
  },
  {
    slug: "sneaker-care-guide",
    title: "The Complete Sneaker Care Guide",
    category: "Sneaker Care",
    featured: true,
    metadata: {
      category: "Sneaker Care",
      guideType: "Care & Maintenance",
      author: "SoleVerse Editorial Team",
      publishedDate: "2026-08-18T06:30:00.000Z",
      readingTime: "8 min read",
      brand: "Nike",
      model: "Air Force 1",
      colorway: "White",
      productCategory: "Lifestyle",
      difficulty: "Beginner",
      bestFor: "Collectors and daily wearers who want to keep kicks fresh",
      keyTakeaways:
        "Clean suede with a dedicated suede brush\nUse a mild soap solution for leather and canvas\nDry sneakers naturally away from direct heat\nProtect suede and nubuck with a spray\nStore pairs with shoe trees to hold their shape",
      recommendedModels:
        "Nike Air Force 1\nadidas Samba OG\nNew Balance 990v6\nConverse Chuck 70\nPuma Suede",
      relatedTopics:
        "Sneaker care\nSuede cleaning\nSneaker storage\nProtectant sprays\nSneaker maintenance",
      metaTitle: "The Complete Sneaker Care Guide | SoleVerse",
      metaDescription:
        "Clean, protect, and store your sneakers properly with the complete SoleVerse sneaker care guide.",
      ogTitle: "The Complete Sneaker Care Guide",
      ogDescription: "Everything you need to keep your sneaker collection looking fresh.",
    },
  },
].map(({ slug, title, category, featured, metadata }, index) => ({
  type: "guide",
  slug,
  title,
  category,
  summary: metadata.keyTakeaways
    ? metadata.keyTakeaways.split("\n")[0]
    : "A practical SoleVerse buying guide.",
  content: `${metadata.bestFor}\n\nKey takeaways:\n${metadata.keyTakeaways}\n\nRecommended models:\n${metadata.recommendedModels}\n\nRelated topics:\n${metadata.relatedTopics}\n\nRead more of this guide on the SoleVerse detail page.`,
  image: pick(IMAGES.guide, index),
  featured,
  status: "published",
  metadata,
}));

export const DEMO_DEALS = [
  {
    slug: "adidas-samba-og-deal",
    title: "adidas Samba OG Core Black — 15% Off",
    category: "Sneakers",
    featured: true,
    metadata: {
      brand: "adidas",
      model: "Samba OG",
      colorway: "Core Black / Gum 4",
      productCategory: "Lifestyle",
      originalPrice: 100,
      salePrice: 85,
      currency: "USD",
      discountPercentage: 15,
      retailer: "adidas",
      affiliateUrl: "https://www.adidas.com/us/samba-OG-ID0478.html",
      productUrl: "https://www.adidas.com/us/samba-OG-ID0478.html",
      couponCode: "SOLEVERSE15",
      availability: "In Stock",
      startDate: "2026-08-08T06:30:00.000Z",
      expirationDate: "2026-09-01T06:30:00.000Z",
      availableSizes: "7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12",
      quickSummary:
        "The classic adidas Samba OG is 15% off, bringing the terrace icon down to $85.",
      whyWeLikeIt:
        "Heritage silhouette that never goes out of style\nPremium leather upper\nGreat price for a classic\nShips from adidas directly",
      dealNotes:
        "Price reflects a limited-time offer\nFree standard shipping on orders over $50\nUse code SOLEVERSE15 at checkout",
      terms:
        "Price and availability may change without notice. Offer is subject to adidas terms and while stocks last.",
      metaTitle: "adidas Samba OG Deal — 15% Off | SoleVerse",
      metaDescription:
        "Save 15% on the adidas Samba OG. Check the latest price, sizes, and deal details on SoleVerse.",
      ogTitle: "adidas Samba OG — 15% Off",
      ogDescription: "Get the adidas Samba OG for $85 instead of $100.",
    },
  },
  {
    slug: "new-balance-990v6-deal",
    title: "New Balance 990v6 Grey Day — 20% Off",
    category: "Sneakers",
    featured: false,
    metadata: {
      brand: "New Balance",
      model: "990v6",
      colorway: "Grey / White",
      productCategory: "Lifestyle",
      originalPrice: 200,
      salePrice: 160,
      currency: "USD",
      discountPercentage: 20,
      retailer: "Foot Locker",
      affiliateUrl: "https://www.footlocker.com/product/new-balance-990v6/",
      productUrl: "https://www.footlocker.com/product/new-balance-990v6/",
      couponCode: "NB20",
      availability: "Low Stock",
      startDate: "2026-08-08T06:30:00.000Z",
      expirationDate: "2026-09-20T06:30:00.000Z",
      availableSizes: "8, 9, 10, 11, 12",
      quickSummary:
        "The premium New Balance 990v6 drops to $160 at Foot Locker while stock lasts.",
      whyWeLikeIt:
        "Best-in-class FuelCell comfort\nPremium Made in USA build\nGreat savings on a $200 retail shoe",
      dealNotes:
        "Low stock on popular sizes\nLimited-time member pricing\nFree shipping for FLX members",
      terms:
        "Deal is subject to Foot Locker availability and may end without notice.",
      metaTitle: "New Balance 990v6 Deal — 20% Off | SoleVerse",
      metaDescription:
        "Save 20% on the New Balance 990v6. Check the latest price, sizes, and availability on SoleVerse.",
      ogTitle: "New Balance 990v6 — 20% Off",
      ogDescription: "Get the New Balance 990v6 for $160 instead of $200.",
    },
  },
  {
    slug: "asics-gel-kayano-14-deal",
    title: "ASICS Gel-Kayano 14 Silver — 25% Off",
    category: "Sneakers",
    featured: false,
    metadata: {
      brand: "ASICS",
      model: "Gel-Kayano 14",
      colorway: "Silver / Blue",
      productCategory: "Running",
      originalPrice: 160,
      salePrice: 120,
      currency: "USD",
      discountPercentage: 25,
      retailer: "ASICS",
      productUrl: "https://www.asics.com/us/en-us/gel-kayano-14/",
      couponCode: "KAYANO25",
      availability: "In Stock",
      startDate: "2026-08-08T06:30:00.000Z",
      expirationDate: "2026-10-01T06:30:00.000Z",
      availableSizes: "7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11",
      quickSummary:
        "The Y2K-favorite ASICS Gel-Kayano 14 is 25% off, now $120 in the silver blue colorway.",
      whyWeLikeIt:
        "Retro runner with modern Gel comfort\nIconic metallic colorway\nStrong discount on a fashion staple",
      dealNotes:
        "Offer applies to select colorways\nFree returns within 30 days\nUse code KAYANO25 at checkout",
      terms:
        "Prices and availability may change. ASICS coupon code terms apply.",
      metaTitle: "ASICS Gel-Kayano 14 Deal — 25% Off | SoleVerse",
      metaDescription:
        "Save 25% on the ASICS Gel-Kayano 14. Check the latest price, sizes, and availability on SoleVerse.",
      ogTitle: "ASICS Gel-Kayano 14 — 25% Off",
      ogDescription: "Get the ASICS Gel-Kayano 14 for $120 instead of $160.",
    },
  },
  {
    slug: "nike-air-force-1-low-deal",
    title: "Nike Air Force 1 Low Triple White — 30% Off",
    category: "Sneakers",
    featured: true,
    metadata: {
      brand: "Nike",
      model: "Air Force 1 Low",
      colorway: "White / White / White",
      productCategory: "Lifestyle",
      originalPrice: 115,
      salePrice: 81,
      currency: "USD",
      discountPercentage: 30,
      retailer: "GOAT",
      affiliateUrl: "https://www.goat.com/sneakers/air-force-1-low-triple-white-cw2288-111",
      productUrl: "https://www.goat.com/sneakers/air-force-1-low-triple-white-cw2288-111",
      couponCode: "GOAT30",
      availability: "In Stock",
      startDate: "2026-08-08T06:30:00.000Z",
      expirationDate: "2026-08-13T06:30:00.000Z",
      availableSizes: "8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13",
      quickSummary:
        "The most iconic white sneaker ever is 30% off — grab the Air Force 1 Triple White for $81 before the deal ends soon.",
      whyWeLikeIt:
        "The definitive clean white sneaker\nHuge 30% discount\nTrusted marketplace authentication",
      dealNotes:
        "Ending soon — offer expires in a few days\nPrice includes authentication\nUse code GOAT30 at checkout",
      terms:
        "Marketplace pricing fluctuates. Deal valid while stock lasts.",
      metaTitle: "Nike Air Force 1 Low Deal — 30% Off | SoleVerse",
      metaDescription:
        "Save 30% on the Nike Air Force 1 Low Triple White. Ending soon — check the latest price and sizes on SoleVerse.",
      ogTitle: "Nike Air Force 1 Low — 30% Off",
      ogDescription: "Get the Nike Air Force 1 for $81 instead of $115.",
    },
  },
  {
    slug: "puma-suede-deal",
    title: "Puma Suede Black — 35% Off",
    category: "Sneakers",
    featured: false,
    metadata: {
      brand: "Puma",
      model: "Suede",
      colorway: "Puma Black / White",
      productCategory: "Lifestyle",
      originalPrice: 85,
      salePrice: 55,
      currency: "USD",
      discountPercentage: 35,
      retailer: "StockX",
      productUrl: "https://stockx.com/puma-suede-black-white",
      couponCode: "STOCKX35",
      availability: "Preorder",
      startDate: "2026-08-08T06:30:00.000Z",
      expirationDate: "2026-09-10T06:30:00.000Z",
      availableSizes: "7, 8, 9, 10, 11",
      quickSummary:
        "The hip-hop classic Puma Suede is 35% off at $55, a steal for a legendary silhouette.",
      whyWeLikeIt:
        "Legendary sneaker at a legendary price\nRich suede upper\nWallet-friendly street style",
      dealNotes:
        "Preorder availability\nShips after authentication\nUse code STOCKX35 at checkout",
      terms:
        "StockX pricing and availability may change. Preorder terms apply.",
      metaTitle: "Puma Suede Deal — 35% Off | SoleVerse",
      metaDescription:
        "Save 35% on the Puma Suede. Check the latest price, sizes, and availability on SoleVerse.",
      ogTitle: "Puma Suede — 35% Off",
      ogDescription: "Get the Puma Suede for $55 instead of $85.",
    },
  },
  {
    slug: "converse-chuck-70-deal",
    title: "Converse Chuck 70 Tri-Panel — 40% Off",
    category: "Sneakers",
    featured: false,
    metadata: {
      brand: "Converse",
      model: "Chuck 70",
      colorway: "White / Black / Gum",
      productCategory: "Lifestyle",
      originalPrice: 90,
      salePrice: 54,
      currency: "USD",
      discountPercentage: 40,
      retailer: "Sneaker Politics",
      productUrl: "https://sneakerpolitics.com/products/converse-chuck-70",
      couponCode: "POLITICS40",
      availability: "Out of Stock",
      startDate: "2026-08-08T06:30:00.000Z",
      expirationDate: "2026-09-05T06:30:00.000Z",
      availableSizes: "8, 9, 10, 11, 12",
      quickSummary:
        "The premium Converse Chuck 70 is 40% off — currently out of stock, so set an alert for the restock.",
      whyWeLikeIt:
        "Premium canvas and cushioning\nDeep 40% discount\nIconic American heritage",
      dealNotes:
        "Currently out of stock — check back soon\nUse code POLITICS40 at checkout\nFree shipping on orders over $75",
      terms:
        "Stock is limited. Deal may be extended at the retailer's discretion.",
      metaTitle: "Converse Chuck 70 Deal — 40% Off | SoleVerse",
      metaDescription:
        "Save 40% on the Converse Chuck 70. Check the latest price, sizes, and restock details on SoleVerse.",
      ogTitle: "Converse Chuck 70 — 40% Off",
      ogDescription: "Get the Converse Chuck 70 for $54 instead of $90.",
    },
  },
].map(({ slug, title, category, featured, metadata }, index) => ({
  type: "deal",
  slug,
  title,
  category,
  summary: metadata.quickSummary,
  content: `${metadata.quickSummary}\n\nWhy we like it:\n${metadata.whyWeLikeIt}\n\nDeal notes:\n${metadata.dealNotes}\n\nTerms:\n${metadata.terms}\n\nRetailer: ${metadata.retailer}. Original price: $${metadata.originalPrice}. Sale price: $${metadata.salePrice}.`,
  image: imageFor(metadata.brand, index),
  featured,
  status: "published",
  metadata,
}));

export const DEMO_CALENDAR = [
  {
    slug: "nike-dunk-low-panda-release",
    title: "Nike Dunk Low \"Panda\" Release",
    category: "Lifestyle",
    featured: false,
    metadata: {
      brand: "Nike",
      model: "Dunk Low",
      colorway: "White / Black",
      category: "Lifestyle",
      sku: "DD1391-100",
      releaseDate: "2026-08-15T06:30:00.000Z",
      releaseType: "General Release",
      availability: "Upcoming",
      region: "Worldwide",
      retailPrice: 115,
      currency: "USD",
      description:
        "The Nike Dunk Low Panda returns in one of the most popular colorways of the last few years, with a clean white and black leather build.",
      metaTitle: "Nike Dunk Low Panda Release Date & Details | SoleVerse",
      metaDescription:
        "Check the Nike Dunk Low Panda release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "adidas-gazelle-hazy-sky-release",
    title: "adidas Gazelle \"Hazy Sky\" Release",
    category: "Lifestyle",
    featured: false,
    metadata: {
      brand: "adidas",
      model: "Gazelle",
      colorway: "Hazy Sky / Gum",
      category: "Lifestyle",
      sku: "BB5480",
      releaseDate: "2026-08-29T06:30:00.000Z",
      releaseType: "General Release",
      availability: "Upcoming",
      region: "Worldwide",
      retailPrice: 90,
      currency: "USD",
      description:
        "The adidas Gazelle gets a soft Hazy Sky suede refresh with a classic gum outsole — an easy-to-wear lifestyle drop.",
      metaTitle: "adidas Gazelle Hazy Sky Release Date | SoleVerse",
      metaDescription:
        "Check the adidas Gazelle Hazy Sky release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "air-jordan-4-military-blue-restock",
    title: "Air Jordan 4 \"Military Blue\" Restock",
    category: "Lifestyle",
    featured: true,
    metadata: {
      brand: "Jordan",
      model: "Air Jordan 4",
      colorway: "White / Military Blue",
      category: "Lifestyle",
      sku: "DH6927-111",
      releaseDate: "2026-09-06T06:30:00.000Z",
      releaseType: "Restock",
      availability: "Upcoming",
      region: "United States",
      retailPrice: 215,
      currency: "USD",
      description:
        "A surprise restock of the Air Jordan 4 Military Blue, one of the most requested retros of the season.",
      metaTitle: "Air Jordan 4 Military Blue Restock Date | SoleVerse",
      metaDescription:
        "Get the Air Jordan 4 Military Blue restock date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "new-balance-9060-marblehead-release",
    title: "New Balance 9060 \"Marblehead\" Release",
    category: "Lifestyle",
    featured: false,
    metadata: {
      brand: "New Balance",
      model: "9060",
      colorway: "Marblehead / Moonbeam",
      category: "Lifestyle",
      sku: "U9060MAE",
      releaseDate: "2026-09-12T06:30:00.000Z",
      releaseType: "General Release",
      availability: "Upcoming",
      region: "Worldwide",
      retailPrice: 150,
      currency: "USD",
      description:
        "The New Balance 9060 lands in a clean Marblehead and Moonbeam colorway that keeps the chunky runner fresh.",
      metaTitle: "New Balance 9060 Marblehead Release Date | SoleVerse",
      metaDescription:
        "Check the New Balance 9060 Marblehead release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "asics-gel-nyc-kithmas-release",
    title: "ASICS Gel-NYC \"Kithmas\" Release",
    category: "Running",
    featured: true,
    metadata: {
      brand: "ASICS",
      model: "Gel-NYC",
      colorway: "Kithmas White / Red",
      category: "Running",
      sku: "1201A918-100",
      releaseDate: "2026-09-19T06:30:00.000Z",
      releaseType: "Limited",
      availability: "Upcoming",
      region: "United States",
      retailPrice: 160,
      currency: "USD",
      description:
        "ASICS teams up for a limited Kithmas edition of the Gel-NYC, blending festive red accents with the model's clean retro runner lines.",
      metaTitle: "ASICS Gel-NYC Kithmas Release Date | SoleVerse",
      metaDescription:
        "Check the limited ASICS Gel-NYC Kithmas release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "puma-mb03-lafrance-release",
    title: "Puma MB.03 \"LaFrancé\" Release",
    category: "Basketball",
    featured: false,
    metadata: {
      brand: "Puma",
      model: "MB.03",
      colorway: "LaFrancé Black / Blue",
      category: "Basketball",
      sku: "377846-01",
      releaseDate: "2026-09-26T06:30:00.000Z",
      releaseType: "Limited",
      availability: "Upcoming",
      region: "Europe",
      retailPrice: 140,
      currency: "USD",
      description:
        "LaMelo Ball's MB.03 gets a LaFrancé-inspired look with bold black and blue paneling and the model's signature alien branding.",
      metaTitle: "Puma MB.03 LaFrancé Release Date | SoleVerse",
      metaDescription:
        "Check the Puma MB.03 LaFrancé release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "converse-chuck-70-earth-tone-release",
    title: "Converse Chuck 70 \"Earth Tone\" Pack Release",
    category: "Lifestyle",
    featured: false,
    metadata: {
      brand: "Converse",
      model: "Chuck 70",
      colorway: "Earth Tone Brown",
      category: "Lifestyle",
      sku: "A00571C",
      releaseDate: "2026-10-10T06:30:00.000Z",
      releaseType: "General Release",
      availability: "Upcoming",
      region: "Europe",
      retailPrice: 95,
      currency: "USD",
      description:
        "The Chuck 70 celebrates natural tones with an earthy brown canvas build and a premium gum sole.",
      metaTitle: "Converse Chuck 70 Earth Tone Release Date | SoleVerse",
      metaDescription:
        "Check the Converse Chuck 70 Earth Tone release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "nike-pegasus-premium-release",
    title: "Nike Pegasus Premium Release",
    category: "Running",
    featured: false,
    metadata: {
      brand: "Nike",
      model: "Pegasus Premium",
      colorway: "Particle Grey / Black",
      category: "Running",
      sku: "FD2291-003",
      releaseDate: "2026-10-17T06:30:00.000Z",
      releaseType: "General Release",
      availability: "Upcoming",
      region: "Worldwide",
      retailPrice: 140,
      currency: "USD",
      description:
        "Nike's Pegasus Premium brings a new level of cushioning and a sculpted midsole to the everyday running icon.",
      metaTitle: "Nike Pegasus Premium Release Date | SoleVerse",
      metaDescription:
        "Check the Nike Pegasus Premium release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "air-jordan-11-bred-release",
    title: "Air Jordan 11 \"Bred\" Release",
    category: "Basketball",
    featured: true,
    metadata: {
      brand: "Jordan",
      model: "Air Jordan 11",
      colorway: "Black / Varsity Red",
      category: "Basketball",
      sku: "378037-061",
      releaseDate: "2026-11-07T06:30:00.000Z",
      releaseType: "Exclusive",
      availability: "Upcoming",
      region: "Worldwide",
      retailPrice: 230,
      currency: "USD",
      description:
        "The holiday season's most anticipated retro — the Air Jordan 11 Bred returns in full patent leather glory.",
      metaTitle: "Air Jordan 11 Bred Release Date | SoleVerse",
      metaDescription:
        "Get the Air Jordan 11 Bred release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "vans-knu-skool-checkerboard-release",
    title: "Vans Knu Skool \"Checkerboard\" Release",
    category: "Skateboarding",
    featured: false,
    metadata: {
      brand: "Vans",
      model: "Knu Skool",
      colorway: "Black / White Checkerboard",
      category: "Skateboarding",
      sku: "VN000CG35F7",
      releaseDate: "2026-11-14T06:30:00.000Z",
      releaseType: "General Release",
      availability: "Upcoming",
      region: "Asia",
      retailPrice: 85,
      currency: "USD",
      description:
        "The chunky Knu Skool gets the checkerboard treatment in a black and white build built for skate and street.",
      metaTitle: "Vans Knu Skool Checkerboard Release Date | SoleVerse",
      metaDescription:
        "Check the Vans Knu Skool Checkerboard release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "asics-gel-kayano-14-silver-blue-release",
    title: "ASICS Gel-Kayano 14 \"Silver Blue\" Release",
    category: "Running",
    featured: false,
    metadata: {
      brand: "ASICS",
      model: "Gel-Kayano 14",
      colorway: "Silver / Blue",
      category: "Running",
      sku: "1201A763-100",
      releaseDate: "2026-12-05T06:30:00.000Z",
      releaseType: "Limited",
      availability: "Upcoming",
      region: "Japan",
      retailPrice: 160,
      currency: "USD",
      description:
        "The Gel-Kayano 14 gets a Japan-exclusive silver and blue build that pairs metallic panels with the model's retro runner comfort.",
      metaTitle: "ASICS Gel-Kayano 14 Silver Blue Release Date | SoleVerse",
      metaDescription:
        "Check the ASICS Gel-Kayano 14 Silver Blue release date, retail price, and release details on SoleVerse.",
    },
  },
  {
    slug: "nike-air-max-90-infrared-release",
    title: "Nike Air Max 90 \"Infrared\" Restock",
    category: "Lifestyle",
    featured: false,
    metadata: {
      brand: "Nike",
      model: "Air Max 90",
      colorway: "Black / Infrared",
      category: "Lifestyle",
      sku: "DH8641-100",
      releaseDate: "2026-12-12T06:30:00.000Z",
      releaseType: "Restock",
      availability: "Upcoming",
      region: "Worldwide",
      retailPrice: 130,
      currency: "USD",
      description:
        "The all-time classic Air Max 90 Infrared returns for the holiday season with its signature infrared accents.",
      metaTitle: "Nike Air Max 90 Infrared Restock Date | SoleVerse",
      metaDescription:
        "Get the Nike Air Max 90 Infrared restock date, retail price, and release details on SoleVerse.",
    },
  },
].map(({ slug, title, category, featured, metadata }, index) => ({
  type: "calendar",
  slug,
  title,
  category,
  summary: metadata.description,
  content: metadata.description,
  image: imageFor(metadata.brand, index),
  featured,
  status: "published",
  metadata,
}));

export const DEMO_ARTICLES = [
  {
    slug: "jordan-brand-confirms-air-jordan-4-military-blue-restock",
    title: "Jordan Brand Confirms Air Jordan 4 \"Military Blue\" Restock",
    category: "Releases",
    tags: ["Jordan", "Restock", "Air Jordan 4"],
    image: pick(IMAGES.jordan, 0),
    featured: true,
    views: 1240,
    content:
      "Jordan Brand has officially confirmed a surprise restock of the Air Jordan 4 Military Blue, one of the most requested retro colorways of the season.\n\nThe restock is scheduled to drop this September across the United States, with a retail price of $215. The build stays true to the 1989 original, featuring a white leather base with military blue accents.\n\nSneakerheads who missed the initial release in 2024 now get another shot at one of the cleanest AJ4 colorways ever made. Keep an eye on the release calendar for raffle details.",
  },
  {
    slug: "adidas-humanrace-samba-hazy-sky-pack",
    title: "adidas and Humanrace Drop the Samba \"Hazy Sky\" Pack",
    category: "Collaborations",
    tags: ["adidas", "Humanrace", "Collaboration"],
    image: pick(IMAGES.nike, 0),
    featured: false,
    views: 890,
    content:
      "adidas and Pharrell Williams' Humanrace have unveiled a new Samba pack that leans into soft, washed-out pastels.\n\nThe lead colorway, Hazy Sky, combines a powder-blue suede upper with a classic gum outsole and co-branded tongue branding. Two additional colorways round out the pack.\n\nHumanrace has quickly built a reputation for quiet luxury takes on adidas classics, and the Hazy Sky Samba continues that theme with muted tones and premium materials.",
  },
  {
    slug: "nike-reports-strong-q1-as-retro-air-demand-holds",
    title: "Nike Reports Strong Q1 Results as Retro Air Demand Holds",
    category: "Industry",
    tags: ["Nike", "Business", "Industry"],
    image: pick(IMAGES.nike, 3),
    featured: false,
    views: 1560,
    content:
      "Nike opened its fiscal year with stronger-than-expected Q1 results, fueled by sustained demand for retro Air franchises including the Air Force 1, Air Max, and Dunk lines.\n\nDirect-to-consumer sales led growth as the brand continues to shift away from wholesale dependence. Footwear revenue rose across North America and Europe.\n\nExecutives credited a focus on freshness in the classic franchise pipeline and strong seasonal sell-through for the quarter's performance.",
  },
  {
    slug: "how-sneaker-resale-is-shifting-in-2026",
    title: "How Sneaker Resale Is Shifting in 2026",
    category: "Culture",
    tags: ["Resale", "Market", "Culture"],
    image: pick(IMAGES.jordan, 3),
    featured: false,
    views: 2130,
    content:
      "The sneaker resale market has matured considerably, with prices stabilizing and buyers becoming more selective.\n\nGrey-market platforms are consolidating, while authentication-first marketplaces continue to grow. Classic silhouettes with strong cultural cachet, like the Air Jordan 1 and Dunk, remain resilient while newer hyped drops cool off faster.\n\nFor buyers, the shifting market means better prices on grails. For collectors, it is a reminder that patience and research still win in the long run.",
  },
  {
    slug: "new-balance-990v6-grey-day-makeover",
    title: "New Balance 990v6 Gets Its First \"Grey Day\" Makeover",
    category: "Brand News",
    tags: ["New Balance", "990v6", "Grey Day"],
    image: pick(IMAGES.nike, 2),
    featured: false,
    views: 980,
    content:
      "New Balance is celebrating Grey Day with a special 990v6 build that layers multiple shades of the brand's signature grey across premium suede, mesh, and leather.\n\nBuilding on the 990 series' reputation for comfort, the release uses the v6's FuelCell midsole for all-day cushioning.\n\nThe Grey Day 990v6 retails for $200 and rolls out globally this September.",
  },
  {
    slug: "return-of-the-puma-speedcat",
    title: "The Return of the Puma Speedcat: How F1 Style Took Over",
    category: "Culture",
    tags: ["Puma", "Speedcat", "Motorsport"],
    image: pick(IMAGES.jordan, 5),
    featured: false,
    views: 1450,
    content:
      "Once a pit-lane staple, the Puma Speedcat has roared back into fashion, appearing on runways, in street style, and across social feeds.\n\nThe slim, low-profile silhouette is a direct nod to 1990s motorsport, and its recent collaborations have pushed it from racing heritage into a full-blown lifestyle hit.\n\nWith prices far below most hype sneakers, the Speedcat is quickly becoming the accessible icon of the current cycle.",
  },
  {
    slug: "asics-retools-gel-kayano-14-for-everyday-wear",
    title: "ASICS Retools the Gel-Kayano 14 for Everyday Wear",
    category: "Brand News",
    tags: ["ASICS", "Gel-Kayano 14", "Running"],
    image: pick(IMAGES.nike, 1),
    featured: false,
    views: 760,
    content:
      "ASICS is leaning further into lifestyle with the Gel-Kayano 14, pairing the retro runner's metallic panels with new everyday-focused colorways.\n\nWhile the 2000s-era stability platform remains performance-capable, ASICS has positioned the model as a fashion staple, with releases landing across global markets.\n\nExpect more colorways and regional exclusives through the end of the year.",
  },
  {
    slug: "vans-brings-back-checkerboard-old-skool",
    title: "Vans Brings Back the Checkerboard Old Skool for Spring",
    category: "Sneaker News",
    tags: ["Vans", "Old Skool", "Checkerboard"],
    image: pick(IMAGES.jordan, 1),
    featured: true,
    views: 1120,
    content:
      "Vans is reviving its most recognizable pattern with a checkerboard take on the Old Skool, landing in stores this fall.\n\nThe black and white checkerboard is printed across a classic suede and canvas upper, finished with the signature white leather side stripe.\n\nPriced at $75, the release is a direct nod to the checkerboard slip-on that became a pop-culture staple in the late 1970s.",
  },
].map((article, index) => ({ ...article, content: article.content }));

export const ALL_DEMO = {
  brands: DEMO_BRANDS,
  releases: DEMO_RELEASES,
  reviews: DEMO_REVIEWS,
  guides: DEMO_GUIDES,
  deals: DEMO_DEALS,
  calendar: DEMO_CALENDAR,
  articles: DEMO_ARTICLES,
};
